services:
  backend:
    build:
      context: ./llm-service
    ports:
      - "9005:8000"
    env_file:
      - ./llm-service/.env
    volumes:
      - ./llm-service/models:/app/models
      - ./llm-service/chroma_db:/app/chroma_db
      - ./dextora_100_questions_clean.csv:/app/dextora_100_questions_clean.csv
    restart: always
